---
- hosts: localhost
  tasks:

    - name: Everyday packages
      apt: name={{ item }} state=present
      with_items:
        - aptitude
        - autojump
        - exuberant-ctags
        - git
        - silversearcher-ag
        - vim

    - name: GUI Packages
      tags: gui
      apt: name={{ item }} state=present
      with_items:
        - i3
        - i3blocks

    - name: Development Packages
      apt: name={{ item }} state=present
      with_items:
        - rake
        - ruby2.1
        - ruby2.1-dev

    # Home directory setup

    - name: Cloning dotfiles
      sudo: yes
      sudo_user: charles
      git: repo=https://github.com/zorab47/dotfiles.git
           dest=/home/charles/.dotfiles
           accept_hostkey=yes


