# sudo ansible -i "localhost," -c local dev.yml
---
- hosts: localhost
  connection: local

  vars:
    user: charles

  tasks:

    - name: Everyday packages
      apt: name={{ item }} state=present
      with_items:
        - aptitude
        - autojump
        - exuberant-ctags
        - git
        - git-extras
        - ranger
        - shellcheck
        - silversearcher-ag
        - tmux
        - vim

    # Neovim
    # ------

    - name: Add neovim PPA repository
      apt_repository: repo='ppa:neovim-ppa/unstable'

    - name: Neovim
      apt: name=neovim

    - name: Symlink .nvimrc to .vimrc
      sudo: yes
      sudo_user: "{{ user }}"
      file: path=/home/{{ user }}/.nvimrc src=/home/{{ user }}/.vimrc state=link

    - name: Symlink .nvim to .vim
      sudo: yes
      sudo_user: "{{ user }}"
      file: path=/home/{{ user }}/.nvim src=/home/{{ user }}/.vim state=link

    # GUI
    # ---

    - name: Add sur5r.net GPG key
      tags: gui
      apt_key: id=0x941c42e6 keyserver=keyserver.ubuntu.com

    - name: Add i3wm repository
      tags: gui
      apt_repository: repo='deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe'

    - name: GUI Packages
      tags: gui
      apt: name={{ item }} state=latest
      with_items:
        - i3
        - i3blocks
        - rxvt-unicode-256color

    - name: dconf gnome-terminal default-show-menubar
      tags: gui
      dconf: user={{ user }}
             key=/org/gnome/terminal/legacy/default-show-menubar
             value=false

    - name: dconf nautilus show-desktop-icons
      dconf: user={{ user }}
             key=/org/gnome/desktop/background/show-desktop-icons
             value=false

    # Ruby
    # ----

    - name: Base development packages
      apt: name={{ item }} state=present
      with_items:
        - autoconf
        - automake
        - bison
        - build-essential
        - curl
        - libreadline6
        - libreadline6-dev
        - libsqlite3-dev
        - libssl-dev
        - libxml2-dev
        - libxslt1-dev
        - libyaml-dev
        - openssl
        - pkg-config
        - zlib1g
        - zlib1g-dev
        - libpq-dev

    - name: Ruby and dev packages
      tags: ruby
      apt: name={{ item }} state=present
      with_items:
        - rake
        - ruby2.1
        - ruby2.1-dev
        - libxml2

    - name: Rubygems
      tags: ruby
      gem: name={{ item }}
      with_items:
        - doing


    # Home directory setup
    # --------------------

    - name: Cloning dotfiles
      sudo: yes
      sudo_user: "{{ user }}"
      git: repo=https://github.com/zorab47/dotfiles.git
           dest=/home/{{ user }}/.dotfiles
           update=no
           accept_hostkey=yes

    - name: Update font caches
      shell: fc-cache -f creates=/home/{{ user }}/.cache/fontconfig

    # ThingM Blink(1)
    # ---------------

    - name: blink(1) dependencies
      tags: blink1
      apt: name={{ item }} state=latest
      with_items:
        - libusb-1.0-0-dev

    - name: Cloning ThingM/blink1 repo
      tags: blink1
      git: repo=https://github.com/ThingM/blink1.git
           dest=/opt/blink1
           recursive=no
           depth=10
           update=no
           accept_hostkey=yes

    - name: Make blink(1)
      tags: blink1
      shell: make
             chdir=/opt/blink1/commandline
             creates=/opt/blink1/commandline/blink1-tool

    - name: Symlink binary to /usr/bin/blink1
      tags: blink1
      file: path=/usr/bin/blink1
            src=/opt/blink1/commandline/blink1-tool
            state=link

    - name: Symlink udev rules 51-blink1.rules
      tags: blink1
      file: path=/etc/udev/rules.d/51-blink1.rules
            src=/opt/blink1/linux/51-blink1.rules
            state=link

