# sudo ansible -i "localhost," -c local work.yml
---
- hosts: localhost
  connection: local
  tasks:

    - name: HipChat GPG key
      tags: hipchat
      apt_key: url=https://www.hipchat.com/keys/hipchat-linux.key

    - name: HipChat repository
      tags: hipchat
      apt_repository: repo='deb http://downloads.hipchat.com/linux/apt stable main'

    - name: Install HipChat
      tags: hipchat
      apt: name=hipchat state=latest

    - name: Add CRAN GPG key
      tags: R
      apt_key: id=0xE084DAB9 keyserver=keyserver.ubuntu.com

    - name: Add CRAN repository
      tags: R
      apt_repository: repo='deb http://cran.rstudio.com/bin/linux/ubuntu {{ ansible_distribution_release }}/'

    - name: Install R
      tags: R
      apt: name=r-base state=latest

    - name: RStudio dependencies
      tags: R
      apt: name={{ item }} state=latest
      with_items:
        - libjpeg62

    - name: RStudio Download
      tags: R
      get_url: url=https://download1.rstudio.org/rstudio-0.99.484-amd64.deb
               dest=/tmp/rstudio-amd64.deb
               validate_certs=no

    - name: VirtualBox GPG key
      tags: virtualbox
      apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc state=present

    - name: VirtualBox repo
      tags: virtualbox
      apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian vivid contrib'

    - name: VirtualBox
      tags: virtualbox
      apt: name={{ item }} state=latest
      with_items:
        - virtualbox-5.0
